version: 2

models:

    - name: sales
      description : informations about turnover, margin, purchase_cost per order
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description : PK -- order's id
            tests : 
            - not_null 

          - name: products_id
            description: id of the product
            tests:
              - not_null

          - name: qty
            description : quantity of products per order

          - name: turnover
            description : revenue per order
            tests:
              - not_null

          - name: purchase_cost
            description : cost of the product
            tests:
              - not_null

          - name: margin
            description : turnover minus purchase_cost